exports_files(["FunctionAnnotatorTestData.bzl"])

exports_files(["StringAnnotatorTestData.bzl"])

exports_files(["UnusedDeclarationTestData.bzl"])

exports_files(["UnresolvedNamedArgumentsAnnotatorTestData.bzl"])

exports_files([
    "LoadedSymbol_defs.bzl",
    "LoadedSymbol_main.bzl",
])
